name: ci
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: make test
  
  test-1:
    name: go-test-1
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: make test
