name: ci
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  validation:
    name: go-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: make test
      - name: Run Lint Check
        run: make lint
  
  lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lint Check
        run: make lint
