name: ci
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: make test
  
  lint:
    name: go-lint
    runs-on: ubuntu-latest
    container:
      image: golang:alpine3.15
    steps:
      - uses: actions/checkout@v3
      - name: Setup Lint Check Environment
        run: |
          go get golang.org/x/tools/cmd/goimports
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Run Lint Check
        run: golangci-lint run
